In [4]:
# import necessary packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from config import DATA_COLUMNS

In [6]:
# load the dataset
df = pd.read_csv("RIL_equity_3_years.csv")
print("The dataset has {} rows and {} columns".format(*df.shape))

The dataset has 492 rows and 13 columns

In [7]:
# display 1st 5 rows of our data
df.head()

,Date,Open Price,High Price,Low Price,Close Price,WAP,No.of Shares,No. of Trades,Total Turnover (Rs.),Deliverable Quantity,% Deli. Qty to Traded Qty,Spread High-Low,Spread Close-Open
0,25-August-2020,2105.00,2111.30,2078.30,2082.00,2089.298804,481884,26648,1.006800e+09,144101,29.90,33.00,-23.00
1,24-August-2020,2098.80,2104.65,2070.15,2096.05,2088.306518,560786,22213,1.171093e+09,162385,28.96,34.50,-2.75
2,21-August-2020,2119.80,2119.80,2077.05,2081.75,2096.925519,437199,19487,9.167737e+08,121391,27.77,42.75,-38.05
3,20-August-2020,2118.05,2123.90,2087.80,2096.35,2108.788895,494200,30536,1.042163e+09,136932,27.71,36.10,-21.70
4,19-August-2020,2141.95,2154.00,2121.35,2133.20,2139.151365,758768,36447,1.623120e+09,204280,26.92,32.65,-8.75

In [8]:
# # display last 5 rows of our data
df.tail()

,Date,Open Price,High Price,Low Price,Close Price,WAP,No.of Shares,No. of Trades,Total Turnover (Rs.),Deliverable Quantity,% Deli. Qty to Traded Qty,Spread High-Low,Spread Close-Open
487,31-August-2018,1273.80,1273.80,1237.05,1240.95,1251.350399,1284024,14772,1.606764e+09,900813,70.16,36.75,-32.85
488,30-August-2018,1300.00,1300.00,1270.45,1274.10,1278.056380,1802595,11065,2.303818e+09,1472726,81.70,29.55,-25.90
489,29-August-2018,1319.00,1328.75,1290.30,1294.45,1309.211052,570571,15437,7.469979e+08,137151,24.04,38.45,-24.55
490,28-August-2018,1298.75,1323.00,1295.50,1318.20,1310.944019,484736,12158,6.354618e+08,115900,23.91,27.50,19.45
491,27-August-2018,1280.05,1296.20,1280.00,1291.60,1290.466958,288953,7343,3.728843e+08,68974,23.87,16.20,11.55

- We have data from 27th August,2018 to 25th August,2020


- *Spread High-Low* and *Spread Close-Open* are derived columns that represent difference between High-Low and Open-Close values respectivly for that day